name: bu-xp-qz-qQre

on:
  workflow_dispatch:
  schedule:
     - cron: '*/20 * * * *'
  watch:
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps: 
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
           node-version: 12.x
      - name: npm install
        run: |
              npm install
      - name: 'run bubb'
        run: |
           node xlcsecret-All.js
        env:
          BBB_bububaoTOKEN: ${{ secrets.BBB_bububaoTOKEN }}
          BBB_CASH: ${{ secrets.BBB_BBB_CASH }}
          SYNCURL: yous/z/Task/bububao.js
          XLC: ${{ secrets.XLC }}
          GITHUB: ${{ secrets.GITHUB }}
          EFORK: ${{ secrets.EFORK }}
          
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
           node-version: 12.x
      - name: npm install
        run: |
              npm install
      - name: 'run ttx'
        run: |
           node xlcsecret-All.js
        env:
          JRTTSIGNURL: ${{ secrets.JRTTSIGNURL }}
          JRTTSIGNKEY: ${{ secrets.JRTTSIGNKEY }}
          JRTTFARMURL: ${{ secrets.JRTTFARMURL }}
          JRTTFARMKEY: ${{ secrets.JRTTFARMKEY }}
          JRTTREADURL: ${{ secrets.JRTTREADURL }}
          JRTTREADKEY: ${{ secrets.JRTTREADKEY }}
          SYNCURL: yous/main/ttjs.js
          XLC: ${{ secrets.XLC }}
          GITHUB: ${{ secrets.GITHUB }}      
          EFORK: ${{ secrets.EFORK }}
          
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: lajigth/you
          ref: 'main'
          token: ${{ secrets.PAT }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: npm install
        run: |
              npm install
              npm install cron
              npm install request
              curl ipinfo.io/json
      - name: 'xiaop'
        run: |
          node xlcsecret-All.js
        env:
           XLC: ${{ secrets.XLC }}
           GITHUB: ${{ secrets.GITHUB }}
           SYNCURL: yous/z/Task/iboxpay.js
           EFORK: ${{ secrets.EFORK }}
          
          
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
           node-version: 12.x
      - name: npm install
        run: |
              npm install
      - name: 'run Qyd'
        run: |
           node xlcsecret-All.js
        env:
          QMYD_qmydTOKEN: ${{ secrets.QMYD_qmydTOKEN }}
          QMYD_CASH: ${{ secrets.QMYD_CASH }}
          SYNCURL: yous/z/Task/qmyd.js
          XLC: ${{ secrets.XLC }}
          GITHUB: ${{ secrets.GITHUB }}
          EFORK: ${{ secrets.EFORK }}

      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
           node-version: 12.x
      - name: npm install
        run: |
              npm install
      - name: 'run QCZJ'
        run: |
           node xlcsecret-All.js
        env:
          QCZJ_GetUserInfoHEADER: ${{ secrets.QCZJ_GetUserInfoHEADER }}
          QCZJ_taskBODY: ${{ secrets.QCZJ_taskBODY }}		
          QCZJ_activityBODY: ${{ secrets.QCZJ_activityBODY }}	
          QCZJ_addCoinBODY: ${{ secrets.QCZJ_addCoinBODY }}
          QCZJ_addCoin2BODY: ${{ secrets.QCZJ_addCoin2BODY }}
          QCZJ_CASH: ${{ secrets.QCZJ_CASH }}
          SYNCURL: yous/z/Task/qczjspeed.js
          XLC: ${{ secrets.XLC }}
          GITHUB: ${{ secrets.GITHUB }}
          EFORK: ${{ secrets.EFORK }}
          
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: lajigth/you
          ref: 'main'
          token: ${{ secrets.PAT }}
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7       
      - name: 'Install requests'
        run: pip install requests
      - name: 'run youthpy'
        run: python3 youth.py
         # 目前最大5个账号
        env:
             BARK: ${{ secrets.BARK }}  #非必须 bark通知
             TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}  #非必须 tg机器人token
             TG_USER_ID: ${{ secrets.TG_USER_ID }}  #非必须 tg机器人userId
             XLC: ${{ secrets.XLC }} 
