name: txN

on:
  workflow_dispatch:
 # schedule:
 #    - cron: '*/5 * * * *'
    repository_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:   
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
           node-version: 12.x
      - name: npm install
        run: |
              npm install
      - name: 'run txn'
        run: |
           node xlcsecret-All.js
        env:
          TXNEWS_SIGN: ${{ secrets.TXNEWS_SIGN }}
          TXNEWS_COOKIE: ${{ secrets.TXNEWS_COOKIE }}
          TXNEWS_VIDEO: ${{ secrets.TXNEWS_VIDEO }}
          SYNCURL: yous/main/txnew.js
          XLC: ${{ secrets.XLC }}
          GITHUB: ${{ secrets.GITHUB }}      
          EFORK: ${{ secrets.EFORK }}
  dispatch:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: ' wait'
        run: |
          sleep 4m
          sleep $(($RANDOM%5))
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          event-type: txn
