name: 'jegotrip_sign'


on:
  push:
  schedule:
    - cron: '0 18 * * *'

jobs:
  autosign:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.10.0
        with:
          php-version: '7.4'

      - name: 'Sign'
        env:
          TASKID: ${{ secrets.TASKID }}
          USERID: ${{ secrets.USERID }}
        run: php wuyouxing.php
        
