name: yout
on:
  #schedule:
   # - cron: '*/15 * * * *'
  workflow_dispatch:
  repository_dispatch:
    types: yout
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:       
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
           node-version: 12.x
      - name: npm install
        run: |
              npm install
      - name: 'run youth'
        run: |
           node xlcsecret-All.js
        env:
          YOUTH_HEADER: ${{ secrets.YOUTH_HEADER }}
          YOUTH_ARTBODY: ${{ secrets.YOUTH_ARTBODY }}
          YOUTH_TIME: ${{ secrets.YOUTH_TIME }}
          SYNCURL: yous/main/youthN.js
          XLC: ${{ secrets.XLC }}
          GITHUB: ${{ secrets.GITHUB }}
          EFORK: ${{ secrets.EFORK }}
          
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
           node-version: 12.x
      - name: npm install
        run: |
              npm install
      - name: 'run txn'
        run: |
           node xlcsecret-All.js
        env:
          TXNEWS_SIGN: ${{ secrets.TXNEWS_SIGN }}
          TXNEWS_COOKIE: ${{ secrets.TXNEWS_COOKIE }}
          TXNEWS_VIDEO: ${{ secrets.TXNEWS_VIDEO }}
          SYNCURL: yous/main/txnew.js
          XLC: ${{ secrets.XLC }}
          GITHUB: ${{ secrets.GITHUB }}      
          EFORK: ${{ secrets.EFORK }}
          
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
           node-version: 12.x
      - name: npm install
        run: |
              npm install
      - name: 'run zm'
        run: |
           node xlcsecret-All.js
        env:
          ZM_zhimabody: ${{ secrets.ZM_zhimabody }}
          ZM_zhimatxbody: ${{ secrets.ZM_zhimatxbody }}
          ZM_CASH: ${{ secrets.ZM_CASH }}
          SYNCURL: yous/z/Task/zhima.js
          XLC: ${{ secrets.XLC }}
          GITHUB: ${{ secrets.GITHUB }}
          EFORK: ${{ secrets.EFORK }}
          
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
           node-version: 12.x
      - name: npm install
        run: |
              npm install
      - name: 'run ttx'
        run: |
           node xlcsecret-All.js
        env:
          JRTTSIGNURL: ${{ secrets.JRTTSIGNURL }}
          JRTTSIGNKEY: ${{ secrets.JRTTSIGNKEY }}
          JRTTFARMURL: ${{ secrets.JRTTFARMURL }}
          JRTTFARMKEY: ${{ secrets.JRTTFARMKEY }}
          JRTTREADURL: ${{ secrets.JRTTREADURL }}
          JRTTREADKEY: ${{ secrets.JRTTREADKEY }}
          SYNCURL: yous/main/ttjs.js
          XLC: ${{ secrets.XLC }}
          GITHUB: ${{ secrets.GITHUB }}      
          EFORK: ${{ secrets.EFORK }}
  dispatch:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: ' wait'
        run: |
          sleep 31m
          sleep $(($RANDOM%5))
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          event-type: yout
